substitutions:
  devicename: atomlite-distance

esphome:
  name: $devicename
  name_add_mac_suffix: true
  platformio_options:
    build_flags:
      - -D CORE_DEBUG_LEVEL=0
      - -D ARDUINO_LOG_LEVEL=0

esp32:
  board: m5stack-atom

external_components:
  - source: components

uart:
  id: uart_sensor
  tx_pin: GPIO32
  rx_pin: GPIO26
  baud_rate: 115200
dfrobot_sen0491:
  uart_id: uart_sensor

sensor:
  - platform: dfrobot_sen0491
    distance:
      name: Distance
      id: distance

wifi:
  reboot_timeout: 15min
  output_power: 15dB
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.7.218
    subnet: 255.255.255.0
    gateway: 192.168.7.1

captive_portal:

improv_serial:

logger:
  level: DEBUG
  logs:
    sensor: WARN

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:
  include_internal: false
  version: 3

safe_mode:
  disabled: true
